# Suppress vitations via remove: true
- id: doi:10.31234/osf.io/mubgv_v4
  remove: true

- id: doi:10.31234/osf.io/mubgv_v3
  remove: true

- id:  doi:10.31234/osf.io/mubgv_v2
  remove: true

- id: doi:10.1080/00223891.2025.2513936
  buttons:
    - type: preprint
      text: "Preprint v1"
      link: https://doi.org/10.31234/osf.io/mubgv
    - type: preprint
      text: "Preprint v2"
      link: https://doi.org/10.31234/osf.io/mubgv_v2
    - type: preprint
      text: "Preprint v3"
      link: https://doi.org/10.31234/osf.io/mubgv_v3
    - type: preprint
      text: "Preprint v4"
      link: https://doi.org/10.31234/osf.io/mubgv_v4
