# Suppress vitations via remove: true
- id: doi:10.31234/osf.io/mubgv_v4
  remove: true

- id: doi:10.31234/osf.io/mubgv_v3
  remove: true

- id:  doi:10.31234/osf.io/mubgv_v2
  remove: true

- id: doi:10.1080/00223891.2025.2513936
  buttons:
    - type: source
      text: Preprint Version 1
      link: https://doi.org/10.31234/osf.io/mubgv
    - type: source
      text: Preprint Version 2
      link: https://doi.org/10.31234/osf.io/mubgv_v2
    - type: source
      text: Preprint Version 3
      link: https://doi.org/10.31234/osf.io/mubgv_v3
    - type: source
      text: Preprint Version 4
      link: https://doi.org/10.31234/osf.io/mubgv_v4
